export const GET_PRODUCTS = 'GET_PRODUCTS'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING'

export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const USERS_LOADING = 'USERS_LOADING'
export const USERS_LOADED = 'USERS_LOADED'

export const ADD_TO_CART = 'ADD_TO_CART'
export const CARTITEMS_LOADING = 'CARTITEMS_LOADING'
export const GET_CARTITEMS = 'GET_CARTITEMS'
export const DELETE_CARTITEM = 'DELETE_CARTITEM'
export const ADD_TO_ORDERHISTORY = 'ADD_TO_ORDERHISTORY'
export const CLEAR_CART = 'CLEAR_CART'
export const ORDERHISTORY_LOADING = 'ORDERHISTORY_LOADING'
export const GET_ORDERHISTORY = 'GET_ORDERHISTORY'
export const ORDERRESULT_LOADING = 'ORDERRESULT_LOADING'
export const GET_ORDERRESULT = 'GET_ORDERRESULT'
export const ORDERDETAIL_LOADING = 'ORDERDETAIL_LOADING'
export const GET_ORDERDETAIL = 'GET_ORDERDETAIL'

export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'



